Repository sequentech/admin-console, pull requests merged in 2023-09, with the labels that each got.

#391 Security updates (#390)
  package.json
  yarn.lock
Labels: dependencies

#392 ✨ Multilingualism (#383)
  avAdmin/admin-directives/ballot-box/view-tally-sheet-modal.html
  avAdmin/admin-directives/ballot-box/write-tally-sheet-modal.html
  avAdmin/admin-directives/create/create.html
  avAdmin/admin-directives/dashboard/dashboard.html
  avAdmin/admin-directives/dashboard/send-auth-codes-modal.js
  avAdmin/admin-directives/elections/elections.html
  avAdmin/admin-sidebar-directive/admin-sidebar-directive.html
Labels: enhancement

#396 Add italian language support
  Gruntfile.js
  locales/it.json
Labels: enhancement

#393 ✨ Role-based login for election manager
  avAdmin/admin-controller/admin-controller.js
  avAdmin/admin-directives/ballot-box/ballot-box.html
  avAdmin/admin-directives/ballot-box/ballot-box.js
  avAdmin/admin-directives/dashboard/dashboard.html
  avAdmin/admin-directives/dashboard/dashboard.js
  avAdmin/admin-directives/elbasic/elbasic.html
  avAdmin/admin-directives/elbasic/elbasic.js
  avAdmin/admin-directives/elcensus/elcensus.html
  avAdmin/admin-directives/elcensus/elcensus.js
  avAdmin/admin-directives/elections/elections.html
  avAdmin/admin-directives/elections/elections.js
  avAdmin/admin-directives/elections/elections.less
  avAdmin/admin-sidebar-directive/admin-sidebar-directive.html
  avAdmin/admin-sidebar-directive/admin-sidebar-directive.js
  avAdmin/init.js
Labels: enhancement, breaking-change

#395 Automated start/stop support
  app.js
  app.less
  avAdmin/admin-directives/activity-log/activity-log.html
  avAdmin/admin-directives/column-filters/datetime/column-filter-datetime.html
  avAdmin/admin-directives/column-filters/datetime/column-filter-datetime.less
  avAdmin/admin-directives/dashboard/dashboard.html
  avAdmin/admin-directives/dashboard/dashboard.js
  avAdmin/admin-directives/dashboard/dashboard.less
  avAdmin/admin-directives/dashboard/scheduled-events-modal.html
  avAdmin/admin-directives/dashboard/scheduled-events-modal.js
  avAdmin/admin-directives/dashboard/scheduled-events-modal.less
  avAdmin/configure-scheduled-events-service.js
  avAdmin/elections-api-service.js
  index.html
  locales/en.json
  vendor/angular-date-picker-polyfill/angular-date-picker-polyfill.js
  vendor/angular-date-picker-polyfill/css/_calendar.less
  vendor/angular-date-picker-polyfill/css/_default_colors.less
  vendor/angular-date-picker-polyfill/css/_default_variables.less
  vendor/angular-date-picker-polyfill/css/_popup.less
  vendor/angular-date-picker-polyfill/css/bootstrap.less
Labels: enhancement

#398 Automated start/stop support (#395)
  app.js
  app.less
  avAdmin/admin-directives/activity-log/activity-log.html
  avAdmin/admin-directives/column-filters/datetime/column-filter-datetime.html
  avAdmin/admin-directives/column-filters/datetime/column-filter-datetime.less
  avAdmin/admin-directives/dashboard/dashboard.html
  avAdmin/admin-directives/dashboard/dashboard.js
  avAdmin/admin-directives/dashboard/dashboard.less
  avAdmin/admin-directives/dashboard/scheduled-events-modal.html
  avAdmin/admin-directives/dashboard/scheduled-events-modal.js
  avAdmin/admin-directives/dashboard/scheduled-events-modal.less
  avAdmin/configure-scheduled-events-service.js
  avAdmin/elections-api-service.js
  index.html
  locales/en.json
  vendor/angular-date-picker-polyfill/angular-date-picker-polyfill.js
  vendor/angular-date-picker-polyfill/css/_calendar.less
  vendor/angular-date-picker-polyfill/css/_default_colors.less
  vendor/angular-date-picker-polyfill/css/_default_variables.less
  vendor/angular-date-picker-polyfill/css/_popup.less
  vendor/angular-date-picker-polyfill/css/bootstrap.less
Labels: enhancement

#399 Fix permissions in some new actions and also in send-auth button
  avAdmin/admin-directives/dashboard/dashboard.html
  avAdmin/admin-directives/dashboard/dashboard.js
Labels: enhancement, breaking-change

#400 🐞 Spinning cog jumps during tally in admin-console
  avAdmin/admin-directives/dashboard/dashboard.js
Labels: bug

#401 Fix status bar action during tally
  avAdmin/admin-directives/dashboard/dashboard.html
Labels: bug
