Repository sequentech/admin-console, pull requests merged in 2023-06, with the labels that each got.

#369 Bump socket.io-parser from 4.0.4 to 4.2.3
  package.json
  yarn.lock
Labels: dependencies

#370 Bump socket.io-parser from 4.0.4 to 4.2.3 (#369)
  package.json
  yarn.lock
Labels: dependencies

#372 Fix css issues on admin console (#371)
  avAdmin/admin-directives/elquestions/elquestions.less
  avAdmin/admin-directives/extra-field/extra-field.less
  avAdmin/admin-directives/question-option-details/question-option-details.less
Labels: bug

#373 Alternative Auth methods support
  avAdmin/admin-directives/dashboard/send-auth-codes-modal-confirm.js
  avAdmin/admin-directives/dashboard/send-auth-codes-modal-confirm.less
  avAdmin/elections-api-service.js
Labels: enhancement

#376 🐞 Census menu translations don't always work
  avAdmin/admin-directives/elcensus/elcensus.html
  avAdmin/admin-directives/elcensus/elcensus.js
Labels: bug

#379 🐞 Census menu translations don't always work (#376)
  avAdmin/admin-directives/elcensus/elcensus.html
  avAdmin/admin-directives/elcensus/elcensus.js
Labels: bug

#375 ✨ Countdown until logout
  SequentConfig.js
Labels: enhancement, breaking-change

#378 `master` branch should be using `master` version number and not `8.0.0`
  Gruntfile.js
  SequentConfig.js
  index.html
  package.json
Labels: bug

#380 Security updates: word-wrap resolution
  package.json
  yarn.lock
Labels: dependencies

#381 Security updates: word-wrap resolution (#380)
  package.json
  yarn.lock
Labels: dependencies

#382 Security updates: word-wrap resolution (#380)
  package.json
  yarn.lock
Labels: dependencies
