Repository sequentech/admin-console, pull requests merged in 2023-01, with the labels that each got.

#331 Migrate from ORT github action to reusable ORT workflow
  .github/workflows/ort.yml
Labels: infrastructure

#332 Migrate from ORT github action to reusable ORT workflow
  .github/workflows/ort.yml
Labels: infrastructure

#333 Error message is not shown on Chrome (Ceremony)
  avAdmin/admin-directives/dashboard/delete-share-ceremony-modal.js
  avAdmin/admin-directives/dashboard/download-share-ceremony-modal.js
  avAdmin/admin-directives/dashboard/login-trustee-ceremony-modal.js
  avAdmin/admin-directives/dashboard/restore-share-ceremony-modal.js
Labels: bug

#334 Error message is not shown on Chrome (Ceremony)
  avAdmin/admin-directives/dashboard/delete-share-ceremony-modal.js
  avAdmin/admin-directives/dashboard/download-share-ceremony-modal.js
  avAdmin/admin-directives/dashboard/login-trustee-ceremony-modal.js
  avAdmin/admin-directives/dashboard/restore-share-ceremony-modal.js
Labels: bug

#323 Live preview
  avAdmin/admin-directives/create/create.html
  avAdmin/admin-directives/create/create.js
  avAdmin/admin-directives/create/create.less
  locales/en.json
  locales/es.json
Labels: enhancement

#335 Live preview (#323)
  avAdmin/admin-directives/create/create.html
  avAdmin/admin-directives/create/create.js
  avAdmin/admin-directives/create/create.less
  locales/en.json
  locales/es.json
Labels: enhancement

#336 Election IDs automation (#330)
  avAdmin/admin-directives/create/create.js
Labels: enhancement
