Repository sequentech/admin-console, pull requests merged in 2024-04, with the labels that each got.

#418 ✨ Election turnout overview / graph for election managers
  Gruntfile.js
  app.js
  app.less
  avAdmin/admin-directives/dashboard/dashboard.html
  avAdmin/admin-directives/dashboard/dashboard.js
  avAdmin/admin-directives/dashboard/turnout-graph.html
  avAdmin/admin-directives/dashboard/turnout-graph.js
  avAdmin/admin-directives/dashboard/turnout-graph.less
  avAdmin/elections-api-service.js
  index.html
  locales/en.json
  locales/es.json
  package.json
Labels: enhancement

#416 ✨ Check if the authorities are online
  avAdmin/admin-directives/create/create.js
  avAdmin/admin-directives/dashboard/dashboard.html
  avAdmin/admin-directives/dashboard/dashboard.js
  avAdmin/admin-directives/dashboard/dashboard.less
  avAdmin/elections-api-service.js
  locales/en.json
  locales/es.json
Labels: enhancement

#419 ✨ Election turnout overview / graph for election managers (#418)
  Gruntfile.js
  app.js
  app.less
  avAdmin/admin-directives/dashboard/dashboard.html
  avAdmin/admin-directives/dashboard/dashboard.js
  avAdmin/admin-directives/dashboard/turnout-graph.html
  avAdmin/admin-directives/dashboard/turnout-graph.js
  avAdmin/admin-directives/dashboard/turnout-graph.less
  avAdmin/elections-api-service.js
  index.html
  locales/en.json
  locales/es.json
  package.json
Labels: enhancement

#420 ✨ Check if the authorities are online (#416)
  avAdmin/admin-directives/create/create.js
  avAdmin/admin-directives/dashboard/dashboard.html
  avAdmin/admin-directives/dashboard/dashboard.js
  avAdmin/admin-directives/dashboard/dashboard.less
  avAdmin/elections-api-service.js
  locales/en.json
  locales/es.json
Labels: enhancement

#415 🐞 Trustees struggle to respond to director
  avAdmin/admin-alerts-directive/admin-alerts-directive.html
  avAdmin/admin-directives/create/create.js
  avAdmin/admin-directives/dashboard/dashboard.js
  avAdmin/elections-api-service.js
  locales/en.json
  locales/es.json
Labels: bug

#422 🛡 Security updates
  package.json
  yarn.lock
Labels: dependencies

#423 🛡 Security updates (#422)
  package.json
  yarn.lock
Labels: dependencies
